# https://docs.docker.com/compose/how-tos/file-watch/

name: bootstrap-proto

services:
    web:
        build: .
        ports:
            - 127.0.0.1:3000:3000
            - 127.0.0.1:3001:3001
        develop:
            watch:
                - action: sync
                  path: ./code
                  target: /app
