# https://docs.docker.com/compose/how-tos/file-watch/

name: bootstrap-proto

services:
    web:
        build: .
        ports:
            - 127.0.0.1:8080:80
        develop:
            watch:
                - action: sync
                  path: ./code
                  target: /usr/local/apache2/htdocs/
